# Generated by Django 4.0.3 on 2022-03-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0002_alter_petition_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
