# Generated by Django 4.0.3 on 2022-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0003_alter_signature_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
