# Generated by Django 4.0.3 on 2022-03-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0004_alter_signature_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='url',
        ),
    ]
