# Generated by Django 4.0.3 on 2022-03-18 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0005_remove_petition_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 3, 18), verbose_name='Дата створення'),
        ),
    ]
