# Generated by Django 4.0.3 on 2022-03-20 00:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petition_service', '0006_alter_petition_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='name',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='surname',
        ),
        migrations.AddField(
            model_name='signature',
            name='signer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 3, 20), verbose_name='Дата створення'),
        ),
    ]
