# Generated by Django 4.0.3 on 2022-04-04 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0007_remove_signature_email_remove_signature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='deleted',
            field=models.BooleanField(default=True, verbose_name='Видалена'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 4, 4), verbose_name='Дата створення'),
        ),
    ]
