# Generated by Django 4.0.3 on 2022-04-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0008_petition_deleted_alter_petition_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Видалена'),
        ),
    ]
