# Generated by Django 4.0.3 on 2022-04-04 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('petition_service', '0010_petition_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 11, 40, 0, 945887, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
